Add discord
php-fig/www.php-fig.org pull request #285
Opened 2020-12-18 20:42 UTC by goetas

2020-12-19 00:36 UTC, Crell commented on source/_layouts/base.twig
> +                    <a class="site_footer_links__link" href="https://disboard.org/server/788815898948665366">Talk on Discord</a>
```suggestion
                    <a class="site_footer_links__link" href="https://disboard.org/server/788815898948665366">Discuss on Discord</a>
```

2020-12-19 00:37 UTC, Crell commented
I think we can get rid of the IRC link.  No one uses it, at all.  And then we can reuse that icon for Discord.

2020-12-19 21:52 UTC, Jean85 requested changes
CSS is not applying color to the Discord icon

![immagine](https://user-images.githubusercontent.com/6729988/102700350-e7de8600-424c-11eb-8811-d1935a9c8e7f.png)

2020-12-20 19:08 UTC, goetas commented
- Added discord icons
- updated text

2020-12-21 10:41 UTC, Jean85 approved these changes

2020-12-21 11:05 UTC, merged